### ISSUE TITLE
Modify the Transpiler to query subclass subgraphs

### ISSUE THREAD

**Issue by richakanwar13** [ranking-agent/reasoner-transpiler#49]
Modify the Transpiler to query subclass subgraphs for [KP Entity subclass semantic operations](https://github.com/RENCI-AUTOMAT/Automat-server/issues/13).

**Comment by richakanwar13** [comment]
Pull request created.

**Comment by mmersmann** [comment]
Reopening to address Transpiler interference with query graph.
